version: '2'

services:
  app:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    expose:
      - "3000"
    env_file:
      - '.env'

  redis:
    image: 'redis:3.2'
    command: "redis-server --requirepass ${REDIS_PASS}"
    volumes:
      - 'redis:/var/lib/redis/data'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - 'app'
    volumes_from:
      - app
volumes:
    redis:
    app:
