version: '2'

services:
  app:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    expose:
      - "3000"
    env_file:
      - '.env'
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

  redis:
    image: 'redis:3.2'
    command: "redis-server --requirepass ${REDIS_PASS}"
    volumes:
      - 'redis:/var/lib/redis/data'
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - 'app'
    volumes_from:
      - app
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

volumes:
    redis:
    app:
