version: '2'

services:
  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - '.:/rails_sandbox'
    env_file:
      - '.env'

  redis:
    image: 'redis:3.2'
    command: "redis-server --requirepass ${REDIS_PASS}"
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
    redis:
