FROM nginx

# Install essentials
RUN apt-get update -qq && apt-get install -y build-essential

# establish where Nginx should look for files
ENV APP_HOME /var/rails_sandbox
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# create log directory
RUN mkdir log

# copy our Nginx config template
COPY config/containers/nginx.conf /tmp/rails_sandbox.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst '$APP_HOME' < /tmp/rails_sandbox.nginx > /etc/nginx/conf.d/default.conf

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]
